language: generic

matrix:
  include:
    - os: linux
      dist: zesty
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/17.04/prod zesty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell

script:
  - pwsh -c 'Import-Module $env:TRAVIS_BUILD_DIR -Scope CurrentUser'
